[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/DankMaterialShell/plugins/Latte"]
    type = "git-repo"
    url = "https://github.com/johndanger/Latte.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/DankMaterialShell/plugins/NightLight"]
    type = "git-repo"
    url = "https://github.com/johndanger/NightLight.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/DankMaterialShell/plugins/dankBitwarden"]
    type = "git-repo"
    url = "https://github.com/Pacman99/DankBitwarden.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"