[".config/DankMaterialShell/plugins/Latte"]
    type = "git-repo"
    url = "https://github.com/johndanger/Latte.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/DankMaterialShell/plugins/NightLight"]
    type = "git-repo"
    url = "https://github.com/johndanger/NightLight.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
